/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\cuterobo.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/cuterobo.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.418, 0]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.BODY} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.SCREEN} />
        <group
          position={[0, 0.001, 0.816]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.148, 0.345, 0.148]}
        >
          <mesh
            geometry={nodes.Cylinder_1.geometry}
            material={materials.BODY}
          />
          <mesh
            geometry={nodes.Cylinder_2.geometry}
            material={materials.Material}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.BODY}
        position={[0, 0, 0.303]}
        rotation={[0, -0.812, 0]}
        scale={[0.319, 0.231, 0.231]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials.BODY}
        position={[0, 0, -0.343]}
        rotation={[0, 0.647, 0]}
        scale={[0.319, 0.231, 0.231]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0.511, 1.473, 0.193]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.197, 0.197, 0.101]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[0.511, 1.478, -0.234]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.197, 0.197, 0.101]}
      />
    </group>
  );
}

useGLTF.preload("/cuterobo.glb");
